import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavLinks from "@/components/navlinks";
import LogoutButton from "@/components/Buttons/logout";
import UserProviderClient from "@/components/providers/UserProviderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Individuella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <UserProviderClient>
      
        <header className="sticky top-0 z-50 bg-white shadow-sm p-4 flex justify-between items-center">
          <NavLinks />
          <LogoutButton />
            <h1 className="text-lg font-semibold text-white-800">
            Individuella uppgift
          </h1>

        </header>
        {children}
        </UserProviderClient>
    
      </body>
    </html>
  );
}
